import { StyleSheet } from 'react-native';
import { theme } from '../../theme';

export const defiColors = {
  bg: '#09090b',
  bgCard: '#18181b',
  bgCardMuted: 'rgba(24, 24, 27, 0.6)',
  bgHeader: 'rgba(24, 24, 27, 0.8)',
  bgInset: 'rgba(9, 9, 11, 0.8)',
  border: '#3f3f46',
  borderMuted: '#27272a',
  textMuted: '#71717a',
  textSecondary: '#a1a1aa',
  gold: '#FDB913',
  goldHover: '#E79300',
  blue: '#60a5fa',
  blueText: '#93c5fd',
  blueMuted: 'rgba(59, 130, 246, 0.1)',
  blueBorder: 'rgba(59, 130, 246, 0.2)',
  purple: '#a78bfa',
  purpleText: '#c4b5fd',
  purpleMuted: 'rgba(168, 85, 247, 0.15)',
  purpleBorder: 'rgba(168, 85, 247, 0.2)',
  amber: '#f59e0b',
  amberText: '#fbbf24',
  emerald: '#34d399',
  rose: '#fb7185',
  buy: '#34d399',
  buyMuted: 'rgba(52, 211, 153, 0.15)',
  sell: '#fb7185',
  sellMuted: 'rgba(251, 113, 133, 0.15)',
};

export const defiStyles = StyleSheet.create({
  pageHeader: { marginBottom: theme.spacing.lg },
  pageTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.h3,
    fontWeight: theme.typography.bold,
    marginBottom: 2,
  },
  pageSubtitle: {
    color: defiColors.textMuted,
    fontSize: theme.typography.tiny,
  },

  hero: {
    backgroundColor: defiColors.bgCard,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: defiColors.border,
    marginBottom: theme.spacing.md,
    overflow: 'hidden',
  },
  heroBody: { padding: theme.spacing.lg },
  heroWalletLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: theme.spacing.sm,
  },
  heroWalletDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(253, 185, 19, 0.8)',
  },
  heroWalletText: {
    color: defiColors.textMuted,
    fontSize: 10,
  },
  heroWalletName: {
    color: defiColors.gold,
    fontFamily: theme.typography.fontFamily.mono,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  heroLabel: {
    color: defiColors.textMuted,
    fontSize: 10,
    fontWeight: theme.typography.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  heroRefreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: 'rgba(82, 82, 91, 0.5)',
  },
  heroRefreshText: {
    color: defiColors.textSecondary,
    fontSize: 10,
    fontWeight: theme.typography.semiBold,
  },
  heroRefreshIcon: { color: defiColors.gold, fontSize: 11 },
  heroBalanceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  heroBalance: {
    color: theme.colors.textPrimary,
    fontSize: 30,
    fontWeight: theme.typography.semiBold,
    fontFamily: theme.typography.fontFamily.mono,
  },
  heroBalanceUnit: {
    color: defiColors.gold,
    fontSize: theme.typography.bodySm,
    fontWeight: theme.typography.semiBold,
  },
  heroUsd: {
    color: defiColors.textSecondary,
    fontSize: theme.typography.bodySm,
    marginTop: 4,
    fontFamily: theme.typography.fontFamily.mono,
  },
  heroNode: {
    color: defiColors.textMuted,
    fontSize: theme.typography.tiny,
    marginTop: theme.spacing.xs,
  },
  heroActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
    marginTop: theme.spacing.lg,
  },
  heroSendBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(231, 147, 0, 0.12)',
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: 'rgba(231, 147, 0, 0.6)',
  },
  heroSendBtnText: {
    color: defiColors.goldHover,
    fontWeight: theme.typography.semiBold,
    fontSize: theme.typography.tiny,
  },
  heroIconBtn: {
    width: 40,
    height: 40,
    borderRadius: theme.borderRadius.sm,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(82, 82, 91, 0.5)',
  },
  heroIconBtnText: {
    color: defiColors.textSecondary,
    fontSize: 10,
    fontWeight: theme.typography.bold,
    letterSpacing: 0.5,
  },
  heroAddress: {
    flex: 1,
    color: defiColors.textSecondary,
    fontSize: 11,
    fontFamily: theme.typography.fontFamily.mono,
    textAlign: 'center',
  },

  section: {
    backgroundColor: defiColors.bg,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: defiColors.border,
    marginBottom: theme.spacing.md,
    overflow: 'hidden',
  },
  sectionDragging: {
    overflow: 'visible',
    zIndex: 20,
    elevation: 8,
  },
  sectionLiquidity: {
    marginBottom: theme.spacing.xxxl,
  },
  sectionHeader: {
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    backgroundColor: defiColors.bgHeader,
    borderBottomWidth: 1,
    borderBottomColor: defiColors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionHeaderPressable: {
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    backgroundColor: defiColors.bgHeader,
    borderBottomWidth: 1,
    borderBottomColor: defiColors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    flexShrink: 1,
  },
  sectionChevron: {
    color: defiColors.textMuted,
    fontSize: 10,
    width: 14,
  },
  sectionTitle: {
    fontSize: theme.typography.caption,
    fontWeight: theme.typography.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  sectionTitleAssets: { color: defiColors.blue },
  sectionTitleOrders: { color: defiColors.purple },
  sectionTitleLiquidity: { color: defiColors.amberText },
  badge: {
    fontSize: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.round,
    fontFamily: theme.typography.fontFamily.mono,
    borderWidth: 1,
  },
  badgeBlue: {
    color: defiColors.blueText,
    backgroundColor: defiColors.blueMuted,
    borderColor: defiColors.blueBorder,
  },
  badgePurple: {
    color: defiColors.purpleText,
    backgroundColor: defiColors.purpleMuted,
    borderColor: defiColors.purpleBorder,
  },
  badgeAmber: {
    color: defiColors.amberText,
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.25)',
  },
  sectionBody: { padding: theme.spacing.md },
  assetDragList: {
    position: 'relative',
    overflow: 'visible',
  },
  sectionFooter: {
    borderTopWidth: 1,
    borderTopColor: defiColors.borderMuted,
    paddingTop: theme.spacing.md,
    marginTop: theme.spacing.sm,
  },
  emptyText: {
    color: defiColors.textMuted,
    fontSize: theme.typography.bodySm,
    textAlign: 'center',
    paddingVertical: theme.spacing.sm,
  },
  hintText: {
    color: defiColors.textMuted,
    fontSize: 11,
    textAlign: 'center',
    marginTop: theme.spacing.sm,
  },

  card: {
    backgroundColor: defiColors.bgCardMuted,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.borderMuted,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  cardInset: {
    backgroundColor: defiColors.bgCard,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.border,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  cardTitle: {
    color: theme.colors.textPrimary,
    fontWeight: theme.typography.semiBold,
    fontSize: theme.typography.body,
  },
  cardSub: {
    color: defiColors.textMuted,
    fontSize: 10,
    fontFamily: theme.typography.fontFamily.mono,
    marginTop: 2,
  },
  encoderBox: {
    backgroundColor: defiColors.bgInset,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.borderMuted,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  encoderTitle: {
    color: defiColors.textSecondary,
    fontSize: theme.typography.caption,
    fontWeight: theme.typography.semiBold,
    marginBottom: theme.spacing.sm,
  },
  encoderRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: theme.spacing.sm,
    flexWrap: 'wrap',
  },
  encoderField: {
    flex: 1,
    minWidth: 90,
  },
  encoderFieldNarrow: {
    width: 72,
  },
  encoderHint: {
    color: defiColors.textMuted,
    fontSize: 10,
    marginBottom: theme.spacing.sm,
  },
  encoderResult: {
    color: defiColors.buy,
    fontSize: theme.typography.caption,
    fontFamily: theme.typography.fontFamily.mono,
    fontWeight: theme.typography.semiBold,
  },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.sm },
  balance: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.mono,
    fontSize: theme.typography.bodySm,
    textAlign: 'right',
  },
  balanceUnit: { color: defiColors.textMuted, fontSize: 10 },

  assetAvatar: {
    width: 36,
    height: 36,
    borderRadius: theme.borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
  },
  assetAvatarImage: {
    width: '100%',
    height: '100%',
  },
  assetAvatarBlue: { backgroundColor: '#2563eb' },
  assetAvatarPurple: { backgroundColor: '#7c3aed' },
  assetAvatarAmber: { backgroundColor: '#d97706' },
  assetAvatarText: {
    color: theme.colors.textPrimary,
    fontWeight: theme.typography.bold,
    fontSize: theme.typography.bodySm,
  },

  tabRow: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.sm, marginBottom: theme.spacing.md },
  tab: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(82, 82, 91, 0.5)',
  },
  tabActive: {
    backgroundColor: 'rgba(231, 147, 0, 0.12)',
    borderColor: 'rgba(231, 147, 0, 0.6)',
  },
  tabText: { color: defiColors.textSecondary, fontSize: theme.typography.tiny, fontWeight: theme.typography.semiBold },
  tabTextActive: { color: defiColors.goldHover },

  compactBtn: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(82, 82, 91, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactBtnActive: {
    backgroundColor: 'rgba(231, 147, 0, 0.12)',
    borderColor: 'rgba(231, 147, 0, 0.6)',
  },
  compactBtnText: {
    color: defiColors.textSecondary,
    fontSize: theme.typography.tiny,
    fontWeight: theme.typography.semiBold,
    textAlign: 'center',
  },
  compactBtnTextActive: { color: defiColors.goldHover },
  compactBtnTextAccent: { color: defiColors.blue },
  compactBtnTextPurple: { color: defiColors.purple },

  input: {
    backgroundColor: defiColors.bgCard,
    color: theme.colors.textPrimary,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.border,
    marginBottom: theme.spacing.sm,
    fontSize: theme.typography.bodySm,
    fontFamily: theme.typography.fontFamily.mono,
  },
  label: { color: defiColors.textSecondary, fontSize: theme.typography.caption, marginBottom: theme.spacing.xs },

  btn: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(82, 82, 91, 0.5)',
    alignItems: 'center',
    marginVertical: theme.spacing.xs,
  },
  btnSecondary: {
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderColor: 'rgba(82, 82, 91, 0.5)',
  },
  btnText: { color: defiColors.textSecondary, fontWeight: theme.typography.semiBold, fontSize: theme.typography.tiny },
  btnTextSecondary: { color: defiColors.textSecondary },
  btnSmall: { paddingVertical: 4, paddingHorizontal: 10, marginVertical: 0 },
  btnDanger: { borderColor: 'rgba(127, 29, 29, 0.6)' },
  btnDangerText: { color: theme.colors.error },
  removeBtn: {
    width: 24,
    height: 24,
    borderRadius: theme.borderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderWidth: 1,
    borderColor: defiColors.borderMuted,
  },
  removeBtnText: { color: defiColors.textSecondary, fontSize: 14, lineHeight: 16 },

  reorderHint: {
    color: defiColors.textMuted,
    fontSize: 10,
  },
  dragHandle: {
    width: 28,
    height: 28,
    borderRadius: theme.borderRadius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(39, 39, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(82, 82, 91, 0.5)',
  },
  dragDotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 12,
    gap: 2,
    justifyContent: 'center',
  },
  dragDot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: defiColors.textSecondary,
    opacity: 0.8,
  },
  cardDragging: {
    opacity: 0.22,
    borderColor: 'rgba(139, 92, 246, 0.4)',
    borderStyle: 'dashed',
  },
  cardDropTarget: {
    borderColor: 'rgba(139, 92, 246, 0.9)',
    backgroundColor: 'rgba(76, 29, 149, 0.22)',
  },
  cardGhostWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 40,
    elevation: 16,
  },
  cardGhost: {
    opacity: 0.96,
    borderColor: 'rgba(139, 92, 246, 0.8)',
    backgroundColor: defiColors.bgCard,
    shadowColor: '#000',
    shadowOpacity: 0.45,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 16,
    transform: [{ scale: 1.02 }],
  },

  orderGroupCard: {
    backgroundColor: defiColors.bgCard,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.border,
    marginTop: theme.spacing.md,
    overflow: 'hidden',
  },
  orderGroupHeader: {
    padding: theme.spacing.md,
    backgroundColor: 'rgba(39, 39, 42, 0.5)',
    gap: theme.spacing.sm,
  },
  orderGroupHeaderExpanded: {
    borderBottomWidth: 1,
    borderBottomColor: defiColors.border,
  },
  orderGroupHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    minWidth: 0,
  },
  orderGroupHeaderBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
    minWidth: 0,
  },
  orderGroupHash: {
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  orderGroupHashText: {
    color: defiColors.textMuted,
    fontSize: 10,
    fontFamily: theme.typography.fontFamily.mono,
  },
  orderGroupChevron: {
    color: defiColors.textMuted,
    fontSize: 12,
    width: 12,
  },
  orderMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
  },
  orderMetaBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: defiColors.bgInset,
    borderWidth: 1,
    borderColor: 'rgba(63, 63, 70, 0.6)',
  },
  orderMetaBadgeText: {
    color: defiColors.textMuted,
    fontSize: 10,
    fontFamily: theme.typography.fontFamily.mono,
  },
  orderMetaBadgePurple: {
    backgroundColor: defiColors.purpleMuted,
    borderColor: defiColors.purpleBorder,
  },
  orderMetaBadgePurpleText: {
    color: defiColors.purpleText,
    fontSize: 10,
    fontFamily: theme.typography.fontFamily.mono,
  },
  orderSubsectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: theme.spacing.sm,
    paddingHorizontal: 4,
  },
  orderSubsectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  orderSubsectionDotBuy: { backgroundColor: defiColors.buy },
  orderSubsectionDotSell: { backgroundColor: defiColors.sell },
  orderSubsectionTitle: {
    fontSize: theme.typography.tiny,
    fontWeight: theme.typography.semiBold,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  orderSubsectionTitleBuy: { color: defiColors.buy },
  orderSubsectionTitleSell: { color: defiColors.sell },
  orderSubsectionCount: { fontSize: theme.typography.tiny },
  orderSubsectionCountBuy: { color: 'rgba(52, 211, 153, 0.7)' },
  orderSubsectionCountSell: { color: 'rgba(251, 113, 133, 0.7)' },
  orderGroupBody: {
    padding: theme.spacing.md,
    gap: theme.spacing.md,
  },

  error: { color: theme.colors.error, fontSize: theme.typography.caption, marginTop: theme.spacing.sm },
  success: { color: theme.colors.success, fontSize: theme.typography.caption, marginTop: theme.spacing.sm },

  orderCard: {
    backgroundColor: defiColors.bgCard,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.border,
    padding: theme.spacing.md,
    marginTop: theme.spacing.sm,
  },
  orderBadge: {
    fontSize: 10,
    fontFamily: theme.typography.fontFamily.mono,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.sm,
    overflow: 'hidden',
  },
  orderBadgeBuy: { color: defiColors.buy, backgroundColor: defiColors.buyMuted },
  orderBadgeSell: { color: defiColors.sell, backgroundColor: defiColors.sellMuted },
  orderLabel: { color: defiColors.textSecondary, fontSize: theme.typography.tiny },
  orderValue: { color: theme.colors.textPrimary, fontSize: theme.typography.caption, fontWeight: theme.typography.semiBold },
  progressTrack: {
    height: 6,
    backgroundColor: defiColors.borderMuted,
    borderRadius: theme.borderRadius.round,
    overflow: 'hidden',
    marginTop: 4,
  },
  progressFillBuy: { height: '100%', backgroundColor: defiColors.buy, borderRadius: theme.borderRadius.round },
  progressFillSell: { height: '100%', backgroundColor: defiColors.sell, borderRadius: theme.borderRadius.round },
  orderDivider: {
    borderTopWidth: 1,
    borderTopColor: defiColors.border,
    marginTop: theme.spacing.sm,
    paddingTop: theme.spacing.sm,
  },
  orderTxLabel: { color: defiColors.textMuted, fontSize: theme.typography.tiny, marginRight: 4 },
  orderTxHash: { color: defiColors.purple, fontSize: theme.typography.tiny, fontFamily: theme.typography.fontFamily.mono },

  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.sm, marginTop: theme.spacing.sm },
  statBox: {
    flex: 1,
    minWidth: '30%',
    backgroundColor: defiColors.bgInset,
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: defiColors.borderMuted,
    padding: theme.spacing.md,
  },
  statLabel: {
    color: defiColors.textMuted,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  statValue: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.body,
    fontWeight: theme.typography.semiBold,
    fontFamily: theme.typography.fontFamily.mono,
  },

  poolCard: {
    backgroundColor: defiColors.bgInset,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    overflow: 'hidden',
    marginBottom: theme.spacing.md,
  },
  poolCardHeader: {
    paddingVertical: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    backgroundColor: defiColors.bgCard,
    borderBottomWidth: 1,
    borderBottomColor: defiColors.borderMuted,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.sm,
  },
  poolCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
    flex: 1,
    minWidth: 0,
  },
  poolAvatar: {
    width: 48,
    height: 48,
    borderRadius: theme.borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  poolAvatarText: {
    color: theme.colors.textPrimary,
    fontWeight: theme.typography.bold,
    fontSize: 22,
  },
  poolPairTitle: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.h3,
    fontWeight: theme.typography.semiBold,
    letterSpacing: -0.5,
  },
  poolPairMeta: {
    color: defiColors.textMuted,
    fontSize: 10,
    fontFamily: theme.typography.fontFamily.mono,
    marginTop: 2,
  },
  poolHashBtn: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  poolHashText: {
    fontFamily: theme.typography.fontFamily.mono,
    fontSize: theme.typography.caption,
    color: defiColors.textSecondary,
  },
  poolHashHint: {
    fontSize: 10,
    marginTop: 2,
  },
  poolCardBody: {
    padding: theme.spacing.lg,
  },
  poolReserveBox: {
    flex: 1,
    minWidth: '30%',
    backgroundColor: defiColors.bgCard,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.border,
    padding: theme.spacing.md,
  },
  poolReserveLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  poolReserveDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  poolReserveLabelText: {
    fontSize: 9,
    fontWeight: theme.typography.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  poolReserveValue: {
    fontSize: 22,
    fontWeight: theme.typography.semiBold,
    fontFamily: theme.typography.fontFamily.mono,
    letterSpacing: -0.5,
  },
  poolReserveUnit: {
    color: defiColors.textMuted,
    fontSize: 10,
    marginTop: 2,
  },
  poolMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.md,
    marginTop: theme.spacing.md,
    paddingHorizontal: 4,
  },
  poolMetaItem: {
    fontSize: theme.typography.bodySm,
  },
  poolMetaCount: {
    fontFamily: theme.typography.fontFamily.mono,
    color: theme.colors.textPrimary,
  },
  lpSharesCard: {
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  lpSharesLabel: {
    fontSize: theme.typography.caption,
    fontWeight: theme.typography.semiBold,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  lpSharesValue: {
    fontSize: 36,
    fontWeight: theme.typography.semiBold,
    fontFamily: theme.typography.fontFamily.mono,
    letterSpacing: -0.5,
    marginTop: 4,
  },
  lpSharesFooter: {
    borderTopWidth: 1,
    paddingTop: theme.spacing.md,
    marginTop: theme.spacing.md,
    fontSize: 10,
  },

  tabBar: {
    backgroundColor: defiColors.bg,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
    borderColor: defiColors.borderMuted,
    padding: 3,
    marginBottom: theme.spacing.md,
  },
  tabBarScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 2,
  },
  tabBarBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: defiColors.goldHover,
    borderWidth: 1,
    borderColor: defiColors.goldHover,
    minHeight: 28,
    justifyContent: 'center',
  },
  tabBarBtnActive: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
  },
  tabBarBtnText: {
    color: '#ffffff',
    fontSize: theme.typography.tiny,
    fontWeight: theme.typography.semiBold,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.88)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.sm,
  },
  modalContent: {
    backgroundColor: defiColors.bg,
    padding: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    width: '100%',
    maxWidth: 480,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: defiColors.border,
    overflow: 'hidden',
  },
  modalAccent: {
    height: 2,
    backgroundColor: defiColors.goldHover,
    opacity: 0.7,
    marginHorizontal: -theme.spacing.lg,
    marginTop: -theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  modalHeader: {
    paddingBottom: theme.spacing.md,
    marginBottom: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: defiColors.borderMuted,
  },
  modalTitle: {
    fontSize: theme.typography.h3,
    color: defiColors.gold,
    fontWeight: theme.typography.semiBold,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  modalSubtitle: {
    fontSize: theme.typography.tiny,
    color: defiColors.textMuted,
    textAlign: 'center',
    marginTop: theme.spacing.xs,
  },
  modalClose: {
    color: defiColors.textSecondary,
    textAlign: 'center',
    marginTop: theme.spacing.lg,
    fontSize: theme.typography.bodySm,
    paddingVertical: theme.spacing.sm,
  },
  modalBlockCounter: {
    backgroundColor: defiColors.bgCard,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: defiColors.borderMuted,
    marginBottom: theme.spacing.md,
  },
  modalBlockText: {
    color: defiColors.textSecondary,
    fontSize: theme.typography.caption,
    fontWeight: theme.typography.semiBold,
  },
});